name: build dns blocklists
on:
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  workflow_dispatch:

permissions:
  contents: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build Block Lists
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get hBlock And Build Blocklists
        id: get-hblock-and-build-blocklists
        shell: bash
        run: |
          set -eou pipefail
          pwd
          ls -A1
          curl -Lo /tmp/hblock https://raw.githubusercontent.com/hectorm/hblock/refs/heads/master/hblock
          chmod -x /tmp/hblock
          mkdir -p /tmp/buildlists/tmp
          bash /tmp/hblock \
                    -S ${{ github.workspace }}/hblock/allowlist.sources \
                    -A none -D none -H none -F none -T "%D" \
                    -O /tmp/buildlists/tmp/allowlist.tmp
          sed -i '/^#/d;/^$/d' /tmp/buildlists/tmp/allowlist.tmp
          sort -u /tmp/buildlists/tmp/allowlist.tmp ${{ github.workspace }}/hblock/allow.list > /tmp/buildlists/tmp/allow.list
          mv /tmp/buildlists/tmp/allow.list ${{ github.workspace }}/hblock/allow.list

          FILE_SIZE_LIMIT=20M
          COMPRESSION_LEVEL=15
          
          echo "make dnsmasq blocklist.conf"
          bash /tmp/hblock \
                    -S ${{ github.workspace }}/hblock/sources.list \
                    -A ${{ github.workspace }}/hblock/allow.list \
                    -D ${{ github.workspace }}/hblock/deny.list \
                    -T "local=/%D/" \
                    -H none -F none \
                    -O /tmp/buildlists/blocklist.conf
          rm -rf dnsmasq.d*
          mkdir -p dnsmasq.d/
          split -dC $FILE_SIZE_LIMIT /tmp/buildlists/blocklist.conf dnsmasq.d/blocklist.conf
          for F in dnsmasq.d/blocklist.conf*; do
              mv -v "$F" "${F%\.*}$(basename "$F" | grep -o '[0-9]*$').conf"
          done
          tar --use-compress-program "zstd --ultra -${COMPRESSION_LEVEL} -T0" \
              -C ${{ github.workspace }}/ -cf dnsmasq.d.tar.zst dnsmasq.d/
          
          echo "make hostfile"
          bash /tmp/hblock \
                    -S ${{ github.workspace }}/hblock/sources.list \
                    -A ${{ github.workspace }}/hblock/allow.list \
                    -D ${{ github.workspace }}/hblock/deny.list \
                    -H none -F none \
                    -O /tmp/buildlists/hosts
          rm -rf hosts.d*
          mkdir -p hosts.d/
          split -dC $FILE_SIZE_LIMIT /tmp/buildlists/hosts hosts.d/hosts
          tar --use-compress-program "zstd --ultra -${COMPRESSION_LEVEL} -T0" \
              -C ${{ github.workspace }}/ -cf hosts.d.tar.zst hosts.d/
          
          echo "make domain only file"
          bash /tmp/hblock \
                    -S ${{ github.workspace }}/hblock/sources.list \
                    -A ${{ github.workspace }}/hblock/allow.list \
                    -D ${{ github.workspace }}/hblock/deny.list \
                    -T "%D" \
                    -H none -F none \
                    -O /tmp/buildlists/domains
          rm -rf domains.d*
          mkdir -p domains.d/
          split -dC $FILE_SIZE_LIMIT /tmp/buildlists/domains domains.d/domains
          tar --use-compress-program "zstd --ultra -${COMPRESSION_LEVEL} -T0" \
              -C ${{ github.workspace }}/ -cf domains.d.tar.zst domains.d/
          
          tree

      - name: Push block list to repo
        id: push-to-repo
        shell: bash
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          #git diff .
          git fetch
          git add -A
          git commit -am "$(date "+%a %b %d %H:%M:%S %Y")"
          git push -u origin main














